### PR TITLE
Fully functional Google authentication ecosystem (Heil pHp)

### PR DESCRIPTION
**Pull request by ankitrai96**
**Complete Authentication ecosystem Via Google**
Now, in true sense, our website has crossed the landing page milestone.
Please visit [http://ebullience.ankitrai.net/] to see it in action

Note: Please note that our discussion on keeping login ecosystem on JS took place **after I finished** working on this. But nevertheless, this can still be used as a fail-safe if and when needed. Especially when considering the fact that no one else has moved past the landing page via google yet!

### CODE REVIEW

**Comment by realslimshanky** [comment]
Great work but due to our unfortunate lack of luxury we cannot host a website with PHP on in since
1) we are using js cookies to do everything 
2) wanna make it even with the entire ecosystem of js
so please make a PR to 'ankit' branch and I'll try to make it work using AJAX calls

**Comment by realslimshanky** [comment]
Bro, 'aaqa' has a working google login using js, gonna test that. In case that's not sufficient for us then we'll move to php.

**Comment by ankitrai96** [comment]
Well bro, it's definitely unfortunate! But what's even more unfortunate is neither do any of us have pleasure of time (which is why I did what has to be done at the first place). And need I remind you, this is that exact FUNCTIONAL prototype which got you the joy to show off. You see, something is better than nothing alas. Besides, this has been pushed to the branch "ankit" already.

**Comment by realslimshanky** [comment]
Yeah! it's working. That's the point. We'll use this if JS doesn't work. Because it'll be a headache if PHP and JS are mixed together with the db. we'll have to manage both from our front end which will take a lot of time for debugging. Hence, make a PR to 'ankit' branch of ebullience.

**Comment by realslimshanky** [comment]
@ankitrai96 thanks buddy :smile:

**Pull request closed without merging**
